#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh .travis/build/build.sh .travis/gen-ssl.sh +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc

install:
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export PROJ_PATH=`pwd`
  - export SSLCERT=$PROJ_PATH/tmp
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql

cache:
  directories:
    - $HOME/.m2

matrix:
  allow_failures:
    - env: DB=build PACKET=8M
      jdk: openjdk11
    - env: DB=mysql:8.0 PACKET=8M ADDITIONAL_CONF=--default-authentication-plugin=mysql_native_password --caching_sha2_password_private_key_path=/etc/sslcert/server.key --caching_sha2_password_public_key_path=/etc/sslcert/public.key
      jdk: openjdk11
  include:
    - env: DB=build PACKET=8M
      jdk: openjdk11
    - env: DB=mysql:5.5 PACKET=8M
      jdk: openjdk11
    - env: DB=mysql:5.6 PACKET=8M
      jdk: openjdk11
    - env: DB=mysql:5.7 PACKET=8M
      jdk: openjdk11
    - env: DB=mysql:8.0 PACKET=8M ADDITIONAL_CONF=--default-authentication-plugin=mysql_native_password --caching_sha2_password_private_key_path=/etc/sslcert/server.key --caching_sha2_password_public_key_path=/etc/sslcert/public.key
      jdk: openjdk11
    - env: DB=mariadb:5.5 PACKET=8M
      jdk: openjdk11
    - env: DB=mariadb:10.1 PACKET=8M
      jdk: openjdk11
    - env: DB=mariadb:10.2 PACKET=8M
      jdk: openjdk11
    - env: DB=mariadb:10.3 PACKET=8M
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M
      jdk: oraclejdk11
    - env: DB=mariadb:10.4 PACKET=8M
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M GALERA=true
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M PROFILE=true
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M TYPE=PREPARE
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M TYPE=REWRITE
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M TYPE=MULTI
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=20M
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=40M
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=40M TYPE=BULK_SERVER
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=40M TYPE=NO_BULK_CLIENT
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=40M TYPE=NO_BULK_SERVER
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=40M COMPRESSION=true
      jdk: openjdk11
    - env: DB=mariadb:10.4 PACKET=8M
      jdk: openjdk12
    - env: DB=mariadb:10.4 PACKET=8M MAXSCALE_VERSION=2.2.9
      jdk: openjdk11

script:
  - if [ "$DB" = "build" ] ; then .travis/build/build.sh; fi
  - if [ "$DB" = "build" ] ; then docker build -t build:latest --label build .travis/build/; fi
  - .travis/script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)