#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com
jdk: openjdk11

before_install:
  - chmod +x .travis/script.sh .travis/build/build.sh .travis/gen-ssl.sh .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc

install:
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export PROJ_PATH=`pwd`
  - export SSLCERT=$PROJ_PATH/tmp
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - export TEST_SERVER_SSL_CERT=$SSLCERT/server.crt
  - export TEST_CLIENT_SSL_CERT=$SSLCERT/client.crt
  - export TEST_CLIENT_KEY=$SSLCERT/client.key

cache:
  directories:
    - $HOME/.m2

matrix:
  allow_failures:
    - env: DB=build
  include:
#    - env: DB=mariadb:5.5
#    - env: DB=mariadb:10.1
#    - env: DB=mariadb:10.2
#    - env: DB=mariadb:10.3
#    - env: DB=mariadb:10.4
#    - env: DB=mariadb:10.4 BENCHMARK=1
#    - env: DB=mariadb:10.5
#    - env: DB=mariadb:10.4 MAXSCALE_VERSION=2.2.9
#    - env: DB=build
#    - env: DB=mysql:5.6
#    - env: DB=mysql:5.7
    - env: DB=mysql:8.0 ADDITIONAL_CONF=--default-authentication-plugin=mysql_native_password --caching_sha2_password_private_key_path=/etc/sslcert/server.key --caching_sha2_password_public_key_path=/etc/sslcert/public.key

script:
  - if [ "$DB" = "build" ] ; then .travis/build/build.sh; fi
  - if [ "$DB" = "build" ] ; then docker build -t build:latest --label build .travis/build/; fi
  - .travis/script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
